version: "3.7"
services:
  app:
    container_name: attendize-app-dev
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    image: ejklock/php-fpm:7.4
    networks:
      - attendizeNetwork
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
      - ./docker-compose/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/app
  db:
    command: --default-authentication-plugin=mysql_native_password
    container_name: attendize-dev-db
    environment:
      MYSQL_DATABASE: attendize
      MYSQL_PASSWORD: attendize
      MYSQL_ROOT_PASSWORD: attendize
      MYSQL_USER: attendize
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    image: mysql:5.7
    networks:
      - attendizeNetwork
    ports:
      - 33306:3306
    restart: unless-stopped
    tty: true
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - attendizeMysqlData:/var/lib/mysql
  nginx:
    container_name: attendize-dev-nginx
    image: nginx:alpine
    networks:
      - attendizeNetwork
    ports:
      - 8000:80
    restart: unless-stopped
    volumes:
      - ./:/var/www/app
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    working_dir: /var/www/app
networks:
  attendizeNetwork:
    driver: bridge
volumes:
  attendizeMysqlData:
    driver: local
    name: attendizeMysqlData
